# Fail/Success Selector.
# By Ed Scrimaglia
---
- name: "*** Bind/Unbind Banner ***"
  hosts: localhost
  gather_facts: False
  
  vars:
    state: absent

  tasks:
    - name: Set Facts
      set_fact:
        state: "{{state}}"
      failed_when: state == 'absent'