# Config Feature, Configuration Any Cisco Feature Service
# By Ed Scrimaglia
---
- name: Select list of servers
  hosts: localhost
  gather_facts: no

  vars_files:
    - ../Data_Model/Service_Model.yaml
  
  tasks:
    - name: Set Facts
      set_fact:
        var_hosts: "{{Service_Model.Env.ansible_hosts}}"
        

- name: Create and activate syslog
  hosts: "{{hostvars['localhost']['var_hosts']}}"
  connection: network_cli
  gather_facts: no
  
  vars_files:
    - ../Data_Model/Service_Model.yaml

  tasks:
    - name: Set Facts
      set_fact:
        debug: "{{Service_Model.Env.debug}}"
        project_path: "{{Service_Model.Env.project_path}}"
        activate_v: true
    
    - name: Activate Feture on devices
      ios_config:
        src: "{{project_path}}/configuraciones/{{inventory_hostname}}_config_feature.cfg"
      register: result
      when: activate_v | bool == true

    - name: Delete Feature on devices
      ios_config:
        src: "{{project_path}}/configuraciones/{{inventory_hostname}}_delete_feature.cfg"
      register: result
      when: activate_v | bool == false

    - name: Show Activate/Delete Feature
      debug:
        var: result
      when: debug == true