# Config Feature, Configuration Any Cisco Feature Service
# By Ed Scrimaglia
---
- name: Select list of servers
  hosts: localhost
  gather_facts: no

  vars_files:
    - ../Data_Model/Service_Model.yaml
  
  tasks:
    - name: Set Facts
      set_fact:
        var_hosts: "{{Service_Model.Env.ansible_hosts}}"
        

- name: Create Features
  hosts: "{{hostvars['localhost']['var_hosts']}}"
  connection: network_cli
  gather_facts: no
  
  vars_files:
    - ../Data_Model/Service_Model.yaml

  tasks:
    - name: Set Facts
      set_fact:
        debug: "{{Service_Model.Env.debug}}"
        project_path: "{{Service_Model.Env.project_path}}"
        activate_v: true
    
    - name: Activate Feture on devices
      block:
        - name: Activate config
          ios_banner:
            banner: login
            text: "{{ lookup('file', '../configuraciones/{{inventory_hostname}}_config_feature.cfg') }}"
            state: present
          register: result
      when: activate_v | bool == true

    - name: Delete Feature on devices
      block:
        - name: Delete config
          ios_banner:
            banner: login
            state: absent
          register: result
      when: activate_v | bool == false

    - name: save running to startup when modified
      ios_config:
        save_when: modified

    - name: Show Activate/Delete Feature
      debug:
        var: result
      when: debug == true